- project:
    check:
      jobs:
        - validate

- job:
    name: validate
    description: Validate manifests, scripts, dependencies and compose the base image
    # Increased timeout as builds can take a while
    timeout: 3600
    run: ci/validate.yaml
    nodeset:
      nodes:
        - name: vm
          # Replace by a fixed version label after branching, once available:
          # https://fedora.softwarefactory-project.io/zuul/labels
          # See: https://pagure.io/fedora-ci/general/issue/474
          # label: cloud-fedora-rawhide-medium
          label: cloud-fedora-40-medium
