 - project:
     check:
       jobs:
         - validate
         - compose-base

 - job:
     name: validate
     description: Validate manifests and scripts syntax
     run: ci/validate.yaml
     nodeset:
       nodes:
         - name: container
           # Replace by a fixed version label after branching, once available:
           # https://fedora.softwarefactory-project.io/zuul/labels
           label: zuul-worker-rawhide

 - job:
     name: compose-base
     description: Test composing the base variant
     timeout: 3600
     run: ci/compose-base.yaml
     nodeset:
       nodes:
         - name: vm
           # Replace by a fixed version label after branching, once available:
           # https://fedora.softwarefactory-project.io/zuul/labels
           label: cloud-fedora-rawhide-medium
